services:
  - type: web
    name: puppeteer-api
    runtime: node
    region: oregon  # ایران نزدیک‌ترین ند رو نداره، ولی oregon یا frankfurt مناسبه
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
